### ISSUE TITLE
[suggestion] Add a bit of a delay before breaking

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#3]
If there's a bit of a delay before it breaks, it feels like you're mining, but more importantly you don't accidentally break something and use up the durability.

**Comment by wowkster** [comment]
Adding in next release

**Comment by mrfloris** [comment]
Excellent, thank you for considering our suggestions.

**Comment by mrfloris** [comment]
Update:

The delay is after breaking the block, which is perfectly fine by me. The goal is to prevent them from quickly breaking 3 blocks in a row and ruining their pickaxe. 

The config file has an option to fine-tune this delay, which is perfect. 

+1 Done.
