### ISSUE TITLE
[request] prevent breaking nether roof

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#5]
Hey, would it be possible to also block y:128 in the nether dimensions? I just tested and went to the nether world and broke through to the roof. I would love to have an option in config.yml to endable/disable this. So on one server i can allow it but disallow it like y:0 in other servers.

**Comment by wowkster** [comment]
Adding config for disabling layers in the next release

**Comment by mrfloris** [comment]
oh wow, awesome! Thanks for making these changes. I'll contribute towards the project with a little pizza-slice donation over paypal in the coming week.

**Comment by mrfloris** [comment]
Update:

The config has a list of levels we can set to prevent breaking bedrock on those levels. For example 0,1,126,127, which is perfect. This now means that they cannot break through the world layer, nor the nether roof, but those servers who still want this can configure it. 

1+ Done!
