### ISSUE TITLE
api version bump

### ISSUE THREAD

**Issue by mrfloris** [wowkster/BedrockMiner#8]
`api-version: 1.14`

Since we're on 1.16.5 now with 1.17 in the summer update, maybe while you are doing updates anyway, could it get a version bump in the api so newer material names are available for craft recipes?

**Comment by wowkster** [comment]
How it works is that I actually code using the 1.16 jar but I set the api version lower so it is backwards compatible. Although the plugin is coded in 1.16, the code should work in 1.14+

Additionally, I'm not yet sure what effect the 1.17 update will have on the spigot api. I may or may not have to update the plugin.

**Comment by mrfloris** [comment]
Thank you for explaining. Appreciated.
